version: '3.8'

services:
  journey-db:
    container_name: journey-db
    env_file:
      - ../../.env/journey-db.env
    image: 'postgres:latest'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    restart: unless-stopped
  accounts-db:
    container_name: accounts-db
    env_file:
      - ../../.env/accounts-db.env
    image: 'postgres:latest'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5431:5432'
    restart: unless-stopped
